# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: grinchfromsmy
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-serverless-app
service: moja-aplikacja-serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true


# daniilmazurenkoapp